// Options: https://stylelint.io/user-guide/rules/

module.exports = {
    "rules": {
        "at-rule-blacklist": ["extend"],
        "at-rule-empty-line-before": ["always", {
            "ignore": ["after-comment", "first-nested", "inside-block", "blockless-after-same-name-blockless", "blockless-after-blockless"],
            "ignoreAtRules": ["else"],
        }],
        "at-rule-name-case": "lower",
        // "at-rule-name-newline-after": "always",
        "at-rule-no-unknown": null,
        "at-rule-no-vendor-prefix": true,
        "at-rule-property-requirelist": {
            "font-face": ["font-family", "font-display", "src"],
        },
        "at-rule-semicolon-newline-after": "always",
        "at-rule-semicolon-space-before": "never",
        // "at-rule-whitelist": [],
        "block-closing-brace-empty-line-before": "never",
        "block-closing-brace-newline-after": ["always", {
            "ignoreAtRules": ["if", "else"],
        }],
        // "block-closing-brace-newline-before": "always",
        // "block-closing-brace-space-after": "never-single-line",
        "block-closing-brace-space-before": "always-single-line",
        "block-no-empty": true,
        // "block-opening-brace-newline-after": "always",
        // "block-opening-brace-newline-before": "never-single-line",
        // "block-opening-brace-space-after": "always-single-line",
        // "block-opening-brace-space-before": "always",
        "color-hex-case": "lower",
        "color-hex-length": "long",
        "color-named": ["never", {
            "ignore": ["inside-function"]
        }],
        "color-no-hex": null,
        "color-no-invalid-hex": true,
        // "comment-empty-line-before": ["always", {"except": ["first-nested"],"ignore": ["after-comment", "stylelint-commands"],}],
        "comment-no-empty": true,
        "comment-whitespace-inside": "always",
        // "comment-word-blacklist": [],
        "custom-media-pattern": null,
        "custom-property-empty-line-before": "never",
        "custom-property-pattern": null,
        "declaration-bang-space-after": "never",
        "declaration-bang-space-before": "always",
        "declaration-block-no-duplicate-properties": [true, {
            "ignore": ["consecutive-duplicates-with-different-values"]
        }],
        "declaration-block-no-redundant-longhand-properties": true,
        "declaration-block-no-shorthand-property-overrides": true,
        "declaration-block-semicolon-newline-after": "always",
        "declaration-block-semicolon-space-after": "always-single-line",
        "declaration-block-semicolon-space-before": "never",
        "declaration-block-single-line-max-declarations": 1,
        "declaration-block-trailing-semicolon": "always",
        "declaration-colon-newline-after": null,
        "declaration-colon-space-after": "always",
        "declaration-colon-space-before": "never",
        "declaration-empty-line-before": null,
        "declaration-no-important": null,
        // "declaration-property-unit-blacklist": {},
        "declaration-property-unit-whitelist": {
            "line-height": []
        },
        // "declaration-property-value-blacklist": {},
        // "declaration-property-value-whitelist": {},
        "font-family-name-quotes": "always-where-recommended",
        "font-family-no-duplicate-names": true,
        "font-family-no-missing-generic-family-keyword": true,
        "font-weight-notation": "numeric",
        // "function-blacklist": [],
        "function-calc-no-invalid": true,
        "function-calc-no-unspaced-operator": true,
        "function-comma-newline-after": "never-multi-line",
        "function-comma-newline-before": "never-multi-line",
        // "function-comma-space-after": "always",
        "function-comma-space-before": "never",
        "function-linear-gradient-no-nonstandard-direction": true,
        "function-max-empty-lines": 0,
        "function-name-case": "lower",
        // "function-parentheses-newline-inside": "never-multi-line",
        // "function-parentheses-space-inside": "never",
        "function-url-no-scheme-relative": true,
        "function-url-quotes": ["always", {
            "except": ["empty"],
        }],
        // "function-url-scheme-blacklist": [],
        // "function-url-scheme-whitelist": [],
        // "function-whitelist": [],
        "function-whitespace-after": "always",
        // "indentation": 4,
        "keyframe-declaration-no-important": true,
        "keyframes-name-pattern": null,
        "length-zero-no-unit": true,
        // "linebreaks": "unix",
        "max-empty-lines": 2,
        // "max-line-length": [50, {"ignore": ["comments"],"ignorePattern": ["/^@import\\s+/", "/^@include\\s+/", "/http?:\/\/[0-9,a-z]*.*/"],}],
        "max-nesting-depth": [3, {
            "ignore": ["blockless-at-rules", "pseudo-classes"],
            "ignoreAtRules": ["for", "each"]
        }],
        "media-feature-colon-space-after": "always",
        "media-feature-colon-space-before": "never",
        // "media-feature-name-blacklist": [],
        "media-feature-name-case": "lower",
        "media-feature-name-no-unknown": true,
        "media-feature-name-no-vendor-prefix": true,
        // "media-feature-name-value-whitelist": [],
        // "media-feature-name-whitelist": [],
        "media-feature-parentheses-space-inside": "never",
        "media-feature-range-operator-space-after": "always",
        "media-feature-range-operator-space-before": "always",
        "media-query-list-comma-newline-after": "never-multi-line",
        "media-query-list-comma-newline-before": "never-multi-line",
        "media-query-list-comma-space-after": "always",
        "media-query-list-comma-space-before": "never",
        "no-descending-specificity": null,
        "no-duplicate-at-import-rules": true,
        "no-duplicate-selectors": true,
        "no-empty-first-line": null,
        "no-empty-source": true,
        "no-eol-whitespace": true,
        "no-extra-semicolons": true,
        "no-invalid-double-slash-comments": null,
        "no-missing-end-of-source-newline": true,
        "no-unknown-animations": true,
        "number-leading-zero": "always",
        "number-max-precision": 5,
        // "number-no-trailing-zeros": true,
        // "property-blacklist": [],
        "property-case": "lower",
        "property-no-unknown": true,
        "property-no-vendor-prefix": true,
        // "property-whitelist": [],
        "rule-empty-line-before": ["always", {
            "ignore": ["after-comment", "first-nested", "inside-block"],
        }],
        "selector-attribute-brackets-space-inside": "never",
        // "selector-attribute-operator-blacklist": [],
        "selector-attribute-operator-space-after": "never",
        "selector-attribute-operator-space-before": "never",
        // "selector-attribute-operator-whitelist": [],
        "selector-attribute-quotes": "always",
        "selector-class-pattern": null,
        // "selector-combinator-blacklist": [],
        "selector-combinator-space-after": "always",
        "selector-combinator-space-before": "always",
        // "selector-combinator-whitelist": [],
        "selector-descendant-combinator-no-non-space": true,
        "selector-id-pattern": null,
        "selector-list-comma-newline-after": "always",
        "selector-list-comma-newline-before": "never-multi-line",
        "selector-list-comma-space-after": "always-single-line",
        "selector-list-comma-space-before": "never",
        "selector-max-attribute": null,
        "selector-max-class": null,
        "selector-max-combinators": null,
        "selector-max-compound-selectors": null,
        "selector-max-empty-lines": 0,
        "selector-max-id": 0,
        "selector-max-pseudo-class": null,
        "selector-max-specificity": null,
        "selector-max-type": null,
        "selector-max-universal": null,
        "selector-nested-pattern": null,
        "selector-no-qualifying-type": null,
        "selector-no-vendor-prefix": true,
        // "selector-pseudo-class-blacklist": [],
        "selector-pseudo-class-case": "lower",
        "selector-pseudo-class-no-unknown": true,
        "selector-pseudo-class-parentheses-space-inside": "never",
        // "selector-pseudo-class-whitelist": [],
        // "selector-pseudo-element-blacklist": [],
        "selector-pseudo-element-case": "lower",
        "selector-pseudo-element-colon-notation": "single",
        "selector-pseudo-element-no-unknown": true,
        // "selector-pseudo-element-whitelist": [],
        "selector-type-case": "lower",
        "selector-type-no-unknown": true,
        "shorthand-property-no-redundant-values": true,
        "string-no-newline": true,
        // "string-quotes": "single",
        "time-min-milliseconds": null,
        // "unit-blacklist": ["em", "rem", "%", "s"],
        "unit-case": "lower",
        "unit-no-unknown": true,
        // "unit-whitelist": ["em", "rem", "%", "s"],
        "value-keyword-case": "lower",
        "value-list-comma-newline-after": "always-multi-line",
        "value-list-comma-newline-before": "never-multi-line",
        "value-list-comma-space-after": "always-single-line",
        "value-list-comma-space-before": "never",
        "value-list-max-empty-lines": 0,
        "value-no-vendor-prefix": true,
    }
};
